### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by lbarwick** [andrewfry/SharpML-Recurrent#1]
Hi Andrew,

I would like to use you LSTM code to research stock price prediction.

Can you give me an idea of how to set-up the DataSet? I have looked in your Example, but I am new to LSTM and would like a pointer on what to put in the DataSequences.

If we could communicate more directly (via email) please let me know how as I am an infrequent GitHub user!

Lawrence.

**Comment by andrewfry** [comment]
Hey I would suggest using something like Tensorflow, Keras or CNTK. This was a demo of how LSTMs work for myself. I rewrote someone else's library in Java to get a better understanding of the inner workings on the LSTMs. You might want to focus on something more achievable that stock price prediction otherwise you will become discouraged.

**Comment by lbarwick** [comment]
Hi Andrew,

Understood, but for my sins, stock prediction is what I do!

I was attracted to your code because it seemed intuitive and easier for me to understand. Do you  feel your LSTM code has any issues, or could I use it as a starter to get myself up the LSTM curve?

I am committed to C#, so Tensorflow and Keras arren't really an option.

**Comment by lbarwick** [comment]
Andrew, I would appreciate the chance to chat less visibly, such that I could share some code, and hopefully get some feedback from you.

Would you be willing to do that? I don't think github has private messaging.

**Comment by andrewfry** [comment]
Hey Man - you can email me andrew (dot) fry (at) gmail (dot) com. Take a look at this presentation.

-A
